In [17]:
# importing the OpenCV library
import cv2
print(cv2.__version__)

4.12.0


In [18]:
# Checking Python Version
!python --version

Python 3.10.11


In [19]:
img_path = r"D:\akashvProfile-TESTO-recorded-InCDAC-Lab\thermal-data\cropped_and_saved\person\frame_000000_person.png"

img = cv2.imread(img_path)
print(img)
print("DataType of img is", type(img))

[[[ 88  88  88]
  [ 88  88  88]
  [ 88  88  88]
  ...
  [102 102 102]
  [102 102 102]
  [102 102 102]]

 [[ 88  88  88]
  [ 88  88  88]
  [ 87  87  87]
  ...
  [102 102 102]
  [102 102 102]
  [102 102 102]]

 [[ 87  87  87]
  [ 88  88  88]
  [ 87  87  87]
  ...
  [102 102 102]
  [102 102 102]
  [102 102 102]]

 ...

 [[ 74  74  74]
  [ 73  73  73]
  [ 72  72  72]
  ...
  [ 95  95  95]
  [ 95  95  95]
  [ 95  95  95]]

 [[ 74  74  74]
  [ 73  73  73]
  [ 73  73  73]
  ...
  [ 95  95  95]
  [ 95  95  95]
  [ 95  95  95]]

 [[ 74  74  74]
  [ 74  74  74]
  [ 73  73  73]
  ...
  [ 95  95  95]
  [ 95  95  95]
  [ 95  95  95]]]
DataType of img is <class 'numpy.ndarray'>


In [20]:
img.shape    # (height, width, channels) of image (ndarray)

(480, 640, 3)

# Displaying the  Image

Waits for a key press

0 → wait forever until key is pressed

👉 Without this:

Window opens and closes instantly

You see nothing

In [21]:
cv2.imshow("My Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()