In [11]:
import cv2
import numpy as np

vid_path = r"D:\Lie Detection Data HTI\Lie_detection_ex2\Thermal_lie_detection_ex2\grey_manual\krishna_grey_manual1.wmv"   # change this
cap = cv2.VideoCapture(vid_path)

# Read first frame
ret, frame = cap.read()
print("Frame shape:", frame.shape)
print("Frame data type:", frame.dtype)
print(frame)

Frame shape: (480, 800, 3)
Frame data type: uint8
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [18]:
bbox = cv2.selectROI("Select Object", frame, False)
cv2.destroyWindow("Select Object")

In [21]:
print("type of bbox:", type(bbox))
print(bbox)       # (x, y, w, h)

type of bbox: <class 'tuple'>
(11, 69, 785, 411)


In [ ]:
def get_mean(bbox, vid_path):
    

    
